### ISSUE TITLE
Can't close the input list

### ISSUE THREAD

**Issue by yoanmalie** [obtuseio/tv#1]
Hello,
I can't close the input list.
When i'm in a movie page if i click on the input i can't close it and this hide the graph.

Thank for this alternative of graphtv.

**Comment by utkarshkukreti** [comment]
Thanks for the report! This has been fixed. I'll deploy shortly and comment here when it's live.

**Comment by utkarshkukreti** [comment]
Deployed: https://tv.obtuse.io/.
