### ISSUE TITLE
Graph full height

### ISSUE THREAD

**Issue by yoanmalie** [obtuseio/tv#2]
I remember there was an option on graphtv that i've used a lot, to have the choice to view the full height of the graph from 0 to 10, or just the compact version, like it is here on tv.obtuse, from the lower note to 10.

**Comment by utkarshkukreti** [comment]
Thanks for the report! This has been fixed. I'll deploy shortly and comment here when it's live.

**Comment by utkarshkukreti** [comment]
Thanks for the report! This has been added. I'll deploy shortly and comment here when it's live.

**Comment by utkarshkukreti** [comment]
Deployed: https://tv.obtuse.io/.
