### ISSUE TITLE
Persist the selected plot options between shows and reloads?

### ISSUE THREAD

**Issue by mthadley** [obtuseio/tv#6]
Really nice job on this app. It's super useful for people who love TV shows.

Right now, if you select "Show Show Trend?", and then navigate to a different show, the application won't remember your selection. Same if you reload the page.

Would it be possible to persist this somehow?

My first thought would be to add something to the query string like `https://tv.obtuse.io/tt0773262?showShowTrend=1`, or something similar?

Thanks!

**Comment by utkarshkukreti** [comment]
I think it would be better if this is just stored in memory so that it persists until the user closes the tab. The settings will persist across searches / opening different shows' pages but not full page reload. Storing it in the URL would be much more complex for little benefit. What do you think?

**Comment by utkarshkukreti** [comment]
I've implemented and deployed this: https://tv.obtuse.io.

**Comment by mthadley** [comment]
@utkarshkukreti Thanks! I think this will make things a lot more convenient.

I still think it would be nice to be able to send a link to someone else and say "Look at the overall trend for this show!" instead of "Hey, go here and click show trend and look at the overall trend!".
But in the end, it's a "nice to have", but not necessary.
